Add Documentation on Load Balancing in UV
titaniumnetwork-dev/Ultraviolet pull request #76
Opened 2023-10-06 10:30 UTC by Notplayingallday383

Hi there, So this PR is a small one and basically adds a bit of documentation of how to load balance your UV instance. Feel free to revise and modify this.

2023-10-09 03:24 UTC, proudparrot2 commented
The now.gg bypass is very unstable rn

2023-10-09 13:00 UTC, Notplayingallday383 commented
> The now.gg bypass is very unstable rn

I know I just replaced the url from actual nowgg to the bypass cus trying to play nowgg without it on UV is just usless lol

2023-10-10 03:06 UTC, wyabubbo commented on README.md
> +Documentation for can be found in the [wiki](https://github.com/titaniumnetwork-dev/Ultraviolet/wiki).
What was the point of editing this?

2023-10-10 10:56 UTC, Notplayingallday383 commented on README.md
> +Documentation for can be found in the [wiki](https://github.com/titaniumnetwork-dev/Ultraviolet/wiki).
oops I made a mistake my bad

2023-10-10 10:58 UTC, Notplayingallday383 commented
I dont know why github isn't saying I updated it but I fixed the spelling mistake

2023-10-10 12:11 UTC, VillainsRule requested changes
this pr sux

2023-10-11 15:54 UTC, closed without merging